MattyA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('signup/', views.signupuser, name="signupuser"),
	path('logout/', views.logoutuser, name='logoutuser'),
	path('login/', views.loginuser, name='loginuser'),    

    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cipher/', include('cipher.urls')),
    path('quiz/', include('quiz.urls')),
]

cipher/urls.py
from django.urls import path
from . import views

app_name='cipher'
urlpatterns = [
    path('', views.cipher, name='cipher'),
    path('result/', views.result, name='result')
]

quiz/urls.py
from django.urls import path
from . import views

app_name='quiz'
urlpatterns = [
    #Quiz
    path('', views.quiz, name='quiz'),
    path('create', views.create, name='create'),
    path('join', views.join, name='join'),
    path('room/<uid>/', views.currentroom, name='currentroom'),

]

MattyA/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

def home(request):
    return render(request, 'MattyA/home.html')

def signupuser(request):
	if request.method == "GET":
		return render(request, 'MattyA/signupuser.html', {'form':UserCreationForm()})
	else:
		if request.POST['password1']==request.POST['password2']:
			try:
				user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
				user.save()
				login(request, user)
				return redirect('home')
			except IntegrityError:
				return render(request, 'MattyA/signupuser.html', {'form':UserCreationForm(), 'error':'That username is already taken'})
		else:
			# Error
			return render(request, 'MattyA/signupuser.html', {'form':UserCreationForm(), 'error':'Passwords did not match'})

@login_required
def logoutuser(request):
	if request.method == "POST":
		logout(request)
		return redirect('home')

def loginuser(request):
	if request.method == "GET":
		return render(request, 'MattyA/loginuser.html', {'form':AuthenticationForm()})
	else:
		user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
		if user is None: return render(request, 'MattyA/loginuser.html', {'form':AuthenticationForm(), 'error':'Username and password did not match'})
		else:
			login(request, user)
			return redirect('home')

MattyA/templates/MattyA/base.html
<!doctype html>
<html lang="en">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
		<div class="container-fluid">	  

			<div class="d-flex flex-row navbar-nav">
			  <li class="nav-item">
				<a href="{% url 'home' %}"><button type="button" class="btn btn-info btn-sm px-2 me-md-2 fw-bold mx-2">Home</button></a>
			  </li>
        {% if user.is_authenticated %}

          <li class="nav-item btn-outline-secondary btn-sm px-2 mx-2">Logged in as {{ user.username }}</li>
          
          <li><form action="{% url 'logoutuser' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm px-2 me-md-2 fw-bold mx-2">Logout</button>
          </form></li>
          
          {% else %}
          
          <li><a href="{% url 'signupuser' %}"><button class="btn btn-primary btn-sm px-2 me-md-2 fw-bold mx-2">Sign Up</button></a></li>
          <li><a href="{% url 'loginuser' %}"><button class="btn btn-primary btn-sm px-2 me-md-2 fw-bold mx-2">Login</button></a></li>
          
          {% endif %} 
              <li class="nav-item btn-outline-secondary btn-sm px-2 mx-2">MattyA.co.uk</li>
              <li class="nav-item list-unstyled">
                <a href="https://www.youtube.com/channel/UC-FZsYPlcdkAXedRyAVK_3A"><button type="button" class="btn btn-outline-secondary btn-sm px-2 mx-2">YouTube</button></a>
            </li>
            <li class="nav-item list-unstyled">
              <a href="https://www.instagram.com/matty314159/"><button type="button" class="btn btn-outline-secondary btn-sm px-2 mx-2">Instagram</button></a>
          </li>
                   
			  
			  
			</div>

		</div>

	  </nav>


    {% block content %}
    {% endblock %}
</body>
</html>

MattyA/templates/MattyA/home.html
{% extends 'MattyA/base.html' %}
{% load static %}
{% block content %}

<div class="text-center"><h1>Matty Artell's homepage </h1><br></div>

<div class="py-5 bg-light text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="/static/images/cipher.png" alt="Cipher preview">
                    <a href="{% url 'cipher:cipher' %}">/cipher/ - A tool for enciphering plaintext</a>
                </div>
              </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="/static/images/qwyf.jpg" alt="Cipher preview">
                  <a href="{% url 'quiz:quiz' %}">/quiz/ - Quiz With Your Friends</a>
                </div>
              </div>
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="/static/images/cipher.png" alt="Cipher preview">
                  Placeholder 2
                </div>
              </div>
        </div>
    </div>
</div>

{% endblock %}

MattyA/templates/MattyA/loginuser.html
{% extends 'MattyA/base.html' %}

{% block content %}

<h1>Login</h1>

<h2> {{ error }}</h2>

<form method="POST"> {% csrf_token %}

{{ form.as_p }}
<button type="submit">Login</button>

</form>

{% endblock %}

MattyA/templates/MattyA/signupuser.html
{% extends 'MattyA/base.html' %}

{% block content %}

<h1>Sign Up</h1>

<h2> {{ error }}</h2>

<form method="POST"> {% csrf_token %}

{{ form.as_p }}
<button type="submit">Sign Up</button>

</form>

{% endblock %}