MattyA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('signup/', views.signupuser, name="signupuser"),
	path('logout/', views.logoutuser, name='logoutuser'),
	path('login/', views.loginuser, name='loginuser'),    

    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cipher/', include('cipher.urls')),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from django.urls import path
from . import views

app_name='quiz'
urlpatterns = [
    #Quiz
    path('', views.quiz, name='quiz'),
    path('create', views.create, name='create'),
    path('join', views.join, name='join'),
    path('room/<uid>/', views.currentroom, name='currentroom'),

]

quiz/models.py
from django.db import models
from .validators import validate_file_size

# Create your models here.

class Room(models.Model):
    
    #Type (individual, team etc)
    class QuizType(models.TextChoices):
        INDIVIDUALS = 'IN'
        TEAMS = 'TE'
        MYSTERY_TEAMS = 'MY'
    quiztype = models.CharField(max_length = 2, choices = QuizType.choices, default = QuizType.INDIVIDUALS)
    roomuid = models.CharField(max_length = 10, unique=True)
    public = models.BooleanField(default=True)
    password = models.CharField(max_length=30)
    questions = models.FileField(upload_to='MEDIA_ROOT/%Y/%m/%d/%S', default='/static/files/default.csv', validators = [validate_file_size])
    #need to verify file-type (with python-magic?)


    def __str__(self):
        return self.roomuid

quiz/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['quiztype', 'public', 'password', 'questions']
        labels = {"questions":("Questions: (.csv file in format \" question, answer, question, answer\" etc)")}

quiz/views.py
from django.shortcuts import render, redirect
from quiz.models import Room
from .forms import RoomForm
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
import random
import csv
import io

# Create your views here.

def genid():
     # Create a new unique 10 char room number
    roomid = ''
    while (len(roomid) < 10):
        chars = 'abcdefghijk1234567890'
        char = random.choice(chars)
        roomid += char
        if Room.objects.filter(roomuid = roomid).exists():
            roomid = ''
            continue
    return(roomid)

def parseqs(csvf):
    #Parse questions & answers from a csv file into a dictionary
    mydict = {}
    decoded_file = csvf.read().decode('utf-8')
    io_string = io.StringIO(decoded_file)
    #print(io_string)
    for line in csv.reader(io_string):
        mydict[line[0]] = line[1]
    return mydict

def quiz(request):
    return render(request, 'quiz/home.html')

@login_required
def create(request):
    if request.method == 'GET':
        return render(request, 'quiz/create.html', {'form':RoomForm()})
    else:
        try:
            roomform = RoomForm(request.POST, request.FILES)
            newroom = roomform.save(commit=False)
            roomid = genid()
            newroom.roomuid = roomid
            newroom.save()
            return redirect('../quiz/room/{}'.format(roomid)) # this is weird, without .. it does /quiz/quiz 
        except ValueError:
            return render(request, 'quiz/create.html', {'form':RoomForm(), 'error':'Files must be .csv of no more than 1MB'})
    #return render(request, 'quiz/create.html', {'myid':roomid})

def join(request):
    if request.method == 'GET':
        return render(request, 'quiz/join.html')
    else:
        uid = request.POST.get('roomid')
        passw = request.POST.get('roompass') 
        try:
            roomobj = Room.objects.get(roomuid = uid)
        except:
            return render(request, 'quiz/join.html', {'error':'Invalid room'})
        print(roomobj)
        if (roomobj.public == False):
            if (passw == roomobj.password):
                return redirect('../quiz/room/{}'.format(uid))
            else:
                return render(request, 'quiz/join.html', {'error':'Incorrect password'})
        else: 
            return redirect('../quiz/room/{}'.format(uid))    

def currentroom(request, uid=0):
    if Room.objects.filter(roomuid = uid).exists():
        roomobj = Room.objects.get(roomuid = uid)
        csvf = roomobj.questions
#        print(csvf)
        qdict = parseqs(csvf)
        print(qdict)
        return render(request, 'quiz/currentroom.html', {'id':uid, 'qdict':qdict})
    else:
        return render(request, 'quiz/home.html', {'error':'{} is not a valid room'.format(uid)})
    

quiz/templates/quiz/create.html
{% extends 'MattyA/base.html' %}
{% load static %}

{% block content %}

<h1>Create a room</h1>

<h2 style="color:red"> {{ error }}</h2>

<form method="POST" enctype="multipart/form-data"> {% csrf_token %}

{{ form.as_p }}
<button type="submit">Create</button>

</form> 

{% endblock %}

quiz/templates/quiz/currentroom.html
{% extends 'MattyA/base.html' %}
{% load static %}

{% block content %}

<h1>Welcome to room {{ id }}</h1>

The questions are: {{ qdict }}

{% endblock %}

quiz/templates/quiz/home.html
{% extends 'MattyA/base.html' %}

{% block content %}

<h1>Quiz With Your Friends</h1>

<h2 style='color:red'>{{ error }}</h2>

{% if user.is_authenticated %}
<h2><a href = "{% url 'quiz:create' %}">Create a room</a></h2><br>
{% endif %}
<h2><a href = "{% url 'quiz:join' %}">Join a room</a></h2>



{% endblock %}

quiz/templates/quiz/join.html
{% extends 'MattyA/base.html' %}

{% block content %}

<h1>Join a room</h1>
<h2 style='color:red'>{{ error }}</h2>
<form method='POST'> {% csrf_token %}
    <label>Enter room id:</label><input type="text" id="roomid" name="roomid">
    <label>Enter room password:</label><input type="text" id="roompass" name="roompass">
    <input type="submit" id="roomidsubmit" value="submit">
</form>


{% endblock %}