MattyA/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('signup/', views.signupuser, name="signupuser"),
	path('logout/', views.logoutuser, name='logoutuser'),
	path('login/', views.loginuser, name='loginuser'),    

    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cipher/', include('cipher.urls')),
    path('quiz/', include('quiz.urls')),
]

cipher/urls.py
from django.urls import path
from . import views

app_name='cipher'
urlpatterns = [
    path('', views.cipher, name='cipher'),
    path('result/', views.result, name='result')
]

quiz/urls.py
from django.urls import path
from . import views

app_name='quiz'
urlpatterns = [
    #Quiz
    path('', views.quiz, name='quiz'),
    path('create', views.create, name='create'),
    path('join', views.join, name='join'),
    path('room/<uid>/', views.currentroom, name='currentroom'),

]

cipher/models.py
from django.db import models

# Create your models here.

cipher/views.py
from django.shortcuts import render
import random

# Create your views here.

def ciphermap(adict, ptext): #given a dictionary which assigns each letter in the alphabet to another letter, returns the ciphertext
    ciphered=''
    for i in range(len(ptext)):
            if not (65<=ord(ptext[i])<=90):
                ciphered+=ptext[i]
                continue
            if not (adict.get(ptext[i])):
                ciphered+=ptext[i]
                continue              
            ciphered+=adict.get(ptext[i])
    return(ciphered)

def alphashift(input, n): #shifts all characters in a string by n characters
    ciphered = ''
    for i in range(len(input)):
            shifted = ord(input[i])
            if not (65<=shifted<=90):
                ciphered+=chr(shifted)
                continue
            if (n>=26):
                n = n % 26
            shifted+=n
            if (shifted > 90):
                while(shifted>90):
                    shifted = shifted - 26
            if (shifted < 65):
                while(shifted < 65):
                    shifted = shifted + 26                
            shifted = chr(shifted)
            ciphered += shifted
    return(ciphered)



def cipher(request):
    return render(request, 'cipher/cipher.html')

def result(request):
    ptext = request.GET.get('plaintext').upper()
    ctype = request.GET.get('type')
    alphabet= list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    alphabet2 = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
    ciphered = ''
    adict = {}
    showtr = False

    if (ctype == 'shift'): # Shifts all characters in the plaintext by shiftby characters
        shiftby = int(request.GET.get('shiftby'))
        ciphered = alphashift(ptext, shiftby)
        return render(request, 'cipher/result.html', {'plaintext':ptext, 'ciphered':ciphered})

    if (ctype == 'rmap'): # Maps each character to a different, randomly chosen character
        rseed = request.GET.get('rseed')
        if not (rseed == ''):
            seed = rseed
            random.seed(seed)        
        key = []
        for i in range(len(alphabet2)): #assigns each letter in the alphabet to another random letter
            rletter = random.randint(0,len(alphabet)-1)
            adict.update({alphabet2[i]:alphabet[rletter]})
            key += alphabet[rletter]
            alphabet.pop(rletter)
        ciphered = ciphermap(adict,ptext)
        rseed = str(rseed)
        mapkey = ''.join(key)
        return render(request, 'cipher/result.html', {'plaintext':ptext, 'ciphered':ciphered, 'mapkey':mapkey})

    if (ctype == 'smap'): # Maps each character to a user-specified character
        map = request.GET.get('maptext').upper()
        alphabet = request.GET.get('alphabet').upper()
        if(map == "" or alphabet == ""):
            return render(request, 'cipher/cipher.html', {'error':"Cipher letters and/or alphabet letters cannot be blank!"})
        elif(len(map)!=len(alphabet)):
            return render(request, 'cipher/cipher.html', {'error':"Map letters and alphabet letters must be the same length!"})
        alphabet = list(alphabet)
        alphabet2 = list(map)
        for i in range(len(alphabet)):
            adict.update({alphabet[i]:alphabet2[i]})
        ciphered = ciphermap(adict,ptext)
        return render(request, 'cipher/result.html', {'plaintext':ptext, 'ciphered':ciphered, 'mapkey':map})

    if (ctype == 'keyword'): # The start of the alphabet is replaced with a keyword, followed by the normal alphabet with repeated letters removed
        keyword = request.GET.get('keywordin').upper()
        keyword2 = ""
        alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
        #remove all duplicate letters in keyword to make a new one
        while len(keyword) > 0:
            first = keyword[0]
            keyword2 += first
            keyword = keyword.replace(first, "")
        #remove all of the resulting letters from the alphabet and insert keyword at the start
        for i in range(len(keyword2)):
            alphabet = alphabet.replace(keyword2[i], "")
        map = list(keyword2 + alphabet)
        alphabet = list(alphabet)
        for i in range(len(alphabet)):
            adict.update({map[i]:alphabet[i]})

        ciphered = ciphermap(adict,ptext)
        map = ''.join(map)
        return render(request, 'cipher/result.html', {'plaintext':ptext, 'ciphered':ciphered, 'mapkey':map})


    if (ctype == 'vigenere'): #this does not work with spaces etc.

        

        keyword = request.GET.get('keywordin').upper()
        keywordconst = request.GET.get('keywordin').upper()

        if(keyword == ""):
            return render(request, 'cipher/cipher.html', {'error':"Keyword cannot be blank"})
        
        #remove all non-letters from keyword
        for i in range(len(keywordconst)):            
            if not (65<=ord(keywordconst[i])<=90):
                keyword = keyword.replace(keywordconst[i], "")

        if (len(keyword) < len(ptext)): #repeats keyword to be as long as ptext            
            current = 0
            while(len(keyword) < len(ptext)):                
                keyword += keyword[current]                
                current += 1

        elif (len(keyword) > len(ptext)): #trims keyword to be as long as ptext
            keyword = keyword[:len(ptext)]

        keyworddisplay = keyword #variable for display before we add spaces to keyword

        for i in range(len(ptext)):
            if not (65<=ord(ptext[i])<=90):
                ciphered+=ptext[i] #the problem is, we will now be using the wrong keyletter
                keyword = keyword[:i] + " " + keyword[i:] #add a space to the keyword at position i to account for this
                continue
            keyletter = ord(keyword[i])
            ptextletter = ord(ptext[i])
            cipheredletter = (keyletter + ptextletter)%26
            ciphered += chr(cipheredletter+65)

        return render(request, 'cipher/result.html', {'plaintext':ptext, 'ciphered':ciphered, 'mapkey':keyworddisplay, 'showtr':True})
      
    return render(request, 'cipher/result.html', {'plaintext':ptext})
    

cipher/templates/cipher/cipher.html
{% extends 'MattyA/base.html' %}

{% block content %}

<script>    
    function check(x) {//function for hiding options until they are needed
        if (x.selectedIndex==0) {
            document.getElementById("submitButton").style.display = 'none';
        } else {
            document.getElementById("submitButton").style.display = 'block';
        
        }
        if (x.selectedIndex==1) { //shift 
            document.getElementById("shift-select").style.display = 'block';
        } else {
            document.getElementById("shift-select").style.display = 'none';
        }
        if (x.selectedIndex==2) { //rmap 
            document.getElementById("rmap-select").style.display = 'block';
        } else {
            document.getElementById("rmap-select").style.display = 'none';
        }
        if (x.selectedIndex==3) { //mapselect 
            document.getElementById("mapselect").style.display = 'block';
        } else {
            document.getElementById("mapselect").style.display = 'none';
        }
        if (x.selectedIndex==4 || x.selectedIndex==5) { //keyword 
            document.getElementById("keyword").style.display = 'block';
        } else {
            document.getElementById("keyword").style.display = 'none';
        }
    }

    function drawgrid(ngrids, nletters) {//function for drawing n grids of n letters

    }

    function validateForm() {
    let keywordin = document.forms["cipherForm"]["keywordin"].value;
    let type = document.forms["cipherForm"]["type"].value;
    let maptext = document.forms["cipherForm"]["maptext"].value;
    let alphabet = document.forms["cipherForm"]["alphabet"].value;
    let shiftby = document.forms["cipherForm"]["shiftby"].value;
    if (keywordin == "" && type == "keyword") {
        alert("Keyword cannot be blank");
        return false;
    }
    if (keywordin == "" && type == "vigenere") {
        alert("Keyword cannot be blank");
        return false;
    }
    if (type == "smap" && maptext.length == 0 || alphabet.length == 0) {
        alert("Map and/or alphabet cannot be blank");
        return false;
    }
    if (type == "smap" && maptext.length != alphabet.length) {
        alert("Map must be the same length as alphabet");
        return false;
    }
    if (type == "shift" && shiftby == "") {
        alert("Shiftby cannot be blank");
        return false;
    }  
}     

</script>

<div class="d-flex justify-content-center text-center">
    {% if error %}
        <h1 style="color:red">{{error}}</h1><br>
    {% endif %}
    <form name="cipherForm" action="{% url 'cipher:result' %}" onsubmit="return validateForm()">
        <h1><label>Plaintext:</label></h1>
        <input type="text" id="plaintext" name="plaintext"><br>

        <h4><label for="type">Select a cipher:</label></h2>

        <select name="type" onChange="check(this);">
           <option selected disabled>Select a cipher type</option>    
           <option value="shift">Shift by n</option>
           <option value="rmap">Random map</option>
           <option value="smap">User-specified map</option>
           <option value="keyword">Keyword cipher</option>
           <option value="vigenere">Vigenere cipher</option>
        </select><br>

        <div id="shift-select" style="display:none;">
            <h4><label>Shift by how many?</label></h4>
        <input type="number" id="shiftby" name="shiftby">
        </div>

        <div id="rmap-select" style="display:none;">
            <h4><label>Enter a random seed:</label></h4>
        <input type="text" id="rseed" name="rseed">
        </div>

        <div id="mapselect" style="display:none;">
            <h4><label>Enter a map</label></h4>
        <label>Plaintext letters: </label><br><input type="text" style="font-family:monospace" id="maptext" name="maptext" size="26"><br>
        <label>Cipher letters:  </label><br><input type="text" style="font-family:monospace" id="alphabet" value="ABCDEFGHIJKLMNOPQRSTUVWXYZ" name="alphabet" size="26">

        <!--<div class = "grid-container"></div>-->

        </div>

        <div id="keyword" style="display:none;">
            <h4><label>What is your keyword?</label></h4>
        <input type="text" id="keywordin" name="keywordin">
        </div><br>


        <input type="submit" id="submitButton" value="Cipherify" style="display:none" class="btn btn-primary btn-sm">
    </form>
</div>
   
</div>

{% endblock %}

cipher/templates/cipher/home.html
{% extends 'cipher/base.html' %}
{% load static %}
{% block content %}

<div class="text-center"><h1>Matty Artell's homepage </h1><br></div>

<div class="py-5 bg-light text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" style="height: 329px; width: 100%; display: block;" src="/static/images/cipher.png" alt="Cipher preview">
                    <a href="{% url 'cipher' %}">/cipher/ - A tool for enciphering plaintext</a>
                </div>
              </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" style="height: 329px; width: 100%; display: block;" src="/static/images/cipher.png" alt="Cipher preview">
                  Placeholder 1
                </div>
              </div>
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" style="height: 329px; width: 100%; display: block;"src="/static/images/cipher.png" alt="Cipher preview">
                  Placeholder 2
                </div>
              </div>
        </div>
    </div>
</div>

{% endblock %}

cipher/templates/cipher/result.html
{% extends 'MattyA/base.html' %}

{% block content %}
    
<div class="col justify-content-center text-center">
<div>Your plaintext was: <h1>{{plaintext}}</h1></div><br>

<div>Your ciphertext is: <h1>{{ciphered}}</h1></div><br>

{% if mapkey %}
    The key is: <h4>{{mapkey}}</h4><br>
{% endif %}

{% if showtr %}
    <br><img src="/static/images/tr.png" alt="Tabula recta"><br>
    To encrypt each letter of the plaintext, follow the row corresponding to the key letter and the column corresponding to the plaintext letter
{% endif %}
</div>

{% endblock %}